name: Deploy to Oracle Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_KEY }}
          port: ${{ secrets.ORACLE_PORT || '22' }}
          script: |
            # Navigate to the project directory
            cd /media/external/disk/pixvas_site
            
            # Pull the latest changes
            git pull origin main
            
            # Rebuild and restart containers
            # -d: Detached mode
            # --build: Build images before starting containers
            docker-compose down
            docker-compose up -d --build
